AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for deploying AWS Network Firewall

Resources:
  VPC3:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.4.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name 
          Value: INSPECTION

  VPC3PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC3
      CidrBlock: 10.4.0.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: INSPECTION Public Subnet 1

  VPC3PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC3
      CidrBlock: 10.4.4.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: INSPECTION Private Subnet 3

  VPC3PrivateSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC3
      CidrBlock: 10.4.5.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]  
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name 
          Value: INSPECTION Private Subnet 4

  VPC3PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC3
      Tags:
        - Key: Name
          Value: Private Route Table (VPC3)

  VPC3DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    DependsOn: NatGateway3
    Properties:
      RouteTableId: !Ref VPC3PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway3
  
  VPC3PrivateSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPC3PrivateSubnet3
      RouteTableId: !Ref VPC3PrivateRouteTable1
  
  VPC3PrivateSubnet4RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPC3PrivateSubnet4
      RouteTableId: !Ref VPC3PrivateRouteTable1

  InternetGateway3:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: INSPECTION IGW

  VPCGatewayAttachment3:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC3
      InternetGatewayId: !Ref InternetGateway3

  VPC3PublicRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC3
      Tags:
        - Key: Name
          Value: Public Route Table (VPC3)

  VPC3DefaultPublicRoute1:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment3
    Properties:
      RouteTableId: !Ref VPC3PublicRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway3

  NatGateway3:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP3.AllocationId
      SubnetId: !Ref VPC3PublicSubnet1

  NatEIP3:
    Type: AWS::EC2::EIP
    DependsOn: InternetGateway3
    Properties:
      Domain: vpc

  VPC3PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPC3PublicSubnet1
      RouteTableId: !Ref VPC3PublicRouteTable1
  
  NetworkFirewall:
    Type: AWS::NetworkFirewall::Firewall
    Properties:
      FirewallName: !Join
        - "-"
        - - "network-firewall"
          - !Ref AWS::Region
      FirewallPolicyArn: !GetAtt NetworkFirewallRulesPolicy.FirewallPolicyArn
      SubnetMappings:
        - SubnetId: !Ref VPC3PrivateSubnet3
        - SubnetId: !Ref VPC3PrivateSubnet4
      VpcId: !Ref VPC3
  
  NetworkFirewallRulesPolicy:
    Type: AWS::NetworkFirewall::FirewallPolicy
    Properties:
      FirewallPolicy:
        StatelessDefaultActions:
          - "aws:pass"
        StatelessFragmentDefaultActions:
          - "aws:pass"
      FirewallPolicyName: !Join
        - "-"
        - - "firewall-policy"
          - !Ref AWS::Region
  
  